### ISSUE TITLE
Menu-on-left ! 

### ISSUE THREAD

**Issue by dragosct10** [timcreative/get-shit-done-pro#43]
1. First step you need to go on html page where you want menu on left and add `menu-on-left` class on body tag.

2. Second you must go on `assets/sass/gsdk/_responsive.scss` and add the following lines of code on line 134: 
```css
.menu-on-left{
        & > .navbar-collapse{
            left: 0;
            right: auto;

            @include transform-translate-x(-230px);
        }

        .nav-open &{
            .wrapper{
                @include transform-translate-x(115px);
            }

            .navbar .container{
                @include transform-translate-x(230px);
            }
        }

        .navbar-header .navbar-toggle{
            float: left;
            margin-right: 0;
            margin-left: 15px;
        }

        .navbar-brand{
            float: right;
        }

        .logo-container{
            float: right;
            margin-right: 40px;
        }
   }
```

3. Compile your scss with  [Koala](http://koala-app.com/) assets/scss/gsdk.scss.
